name: python-pcl
channels:
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'menpo'
- !!python/unicode
  'sirokujira'
- !!python/unicode
  'defaults'
dependencies:
  - Cython=0.28.5
  - pcl=1.8.1
  - vtk=8.0.1
  - matplotlib
  - numpy
